[project]
name = "funtalk"
version = "1.0.28"
description = "funtalk"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "edge-tts~=6.1.10",
    "funutil",
    "moviepy",
    "openai-whisper",
    "tqdm",
]
[[project.authors]]
name = "niuliangtao"
email = "farfarfun@qq.com"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.setuptools]
license-files = []

[dependency-groups]
dev = [
    "pytest",
]
